# Use this file to construct an environment
# for developing ibroadcast from source.
#
#   mamba env create -f dev-environment.yml
#   mamba activate ibroadcast-dev

name: ibroadcast-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  # Project dependencies
  - requests
  # Project from source
  - pip
  - pip:
    - -e .
